### ISSUE TITLE
How to pair with Nuki?

### ISSUE THREAD

**Issue by csuermann** [as19git67/nukible#1]
I'm trying to run `node ./sample/main.js` but all I get is

    initial configuration saved
    No locks paired

Apart from initiating pairing mode on the Nuki itself by pressing the button for 5 seconds, what else does it take to actually pair nukible with Nuki?

I appreciate any hint!

Thank you!

**Comment by JohnMcLear** [comment]
@as19git67 any input on this?

**Comment by as19git67** [comment]
I've updated the sample/main.js to allow pressing p when no lock is already paired

**Comment by as19git67** [comment]
seems to work now

**Comment by JohnMcLear** [comment]
Nice thanks ,I will test now.

**Comment by JohnMcLear** [comment]
Tested, works :) Thanks!
