### ISSUE TITLE
NUKI Smart Lock 3.0

### ISSUE THREAD

**Issue by markokitanoski1** [as19git67/nukible#11]
Hello,

i am trying to use this nukible.js script in my development for pairing process with my NUKI Smart Lock 3.0 device, but I can not manage to get it work. The stuff just hangs up at the "Step 4: SL sent first part of public key.." as does not proceed in the switch case of "nukible.prototype.STATE_PAIRING_CL_REQ_PUBKEY_FIN" for further process of pairing. Is this script working as well as with the NUKI Smart Lock 3.0 or there might be some problems? If does not, could it be  somehow udpated to sort out the things 3.0 smart lock expects and manage to get it work with the 3.0 lock as well?

I would very much appreciate for the help by the developer team of this repo. Thanks in advance!

**Comment by as19git67** [comment]
I don't have a Nuki Smartlock V2 or V3 and so I can't reproduce this issue.

**Comment by markokitanoski1** [comment]
I can relate that with some minor modifications to the existing Nuki Smart Lock V1 implementation, the code works as well with the Nuki Smart Lock V3.

**Comment by as19git67** [comment]
Would you like to share what the modifications are?
